name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@45471b560aceda922ebec22a20b72f0c29914cad # v15.1.0

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@45471b560aceda922ebec22a20b72f0c29914cad # v15.1.0

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@45471b560aceda922ebec22a20b72f0c29914cad # v15.1.0
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}

  docs:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: darbiadev/.github/.github/workflows/github-pages-python-sphinx.yaml@45471b560aceda922ebec22a20b72f0c29914cad # v15.1.0
